lexik_jwt_authentication:
    public_key:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    secret_key:  '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:   3600
